spring:
  application:
    name: config-service
  cloud:
      config:
        server:
          git:
            uri: https://github.com/kolamylopin/spring-config.git
            clone-on-start: true
server:
  port: 8888
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
