spring:
  application:
    name: config-service
  cloud:
      config:
        server:
          accept-empty: false
          git:
            uri: https://github.com/kolamylopin/spring-config.git
            clone-on-start: true
server:
  port: 8888
eureka:
  client:
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
  instance:
        lease-renewal-interval-in-seconds: 5
        lease-expiration-duration-in-seconds: 10